name: vasanth-1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first-step"
      - run: date
      - run: df -h
      - run: free -h
      - run: date
      - run: hostname
         
