name: test-if
on: push
jobs:
   test:
     runs-on: ubuntu-latest
     steps:
        - name: run if or
          if: github.actor == 'prabhas'  ||  github.actor == 'prabhas2612'
          run: echo "triggered"
